### ISSUE TITLE
ゲーム進行部分の実装

### ISSUE THREAD

**Issue by yalogic** [taketoyoshida/ToTH-Client#34]
### Idea (提案する内容)

ゲームを動かすクラスを実装したい

### Impact (提案による変更の影響範囲)

必要ですよね？

### Note (補足・考慮すべきこと)

どこにどんな感じでクラスを置けば良いでしょうか
ControllerにGachaクラスと並列する感じ？

**Comment by shion1305** [comment]
画面要素については `view.game` パッケージ、 ゲーム進行のデータ操作については `controller.game` に追加する感じでお願いします～

**Comment by nagry15** [comment]
controller.home.game にゲーム進行のデータ操作を書けばいい？

**Comment by yalogic** [comment]
controller下にゲームパッケージ作っているんですがOK?

**Comment by shion1305** [comment]
それでおねがい！
