### ISSUE TITLE
✨プレイヤーの攻撃がかち合った場合の処理

### ISSUE THREAD

**Issue by kaneko-shoi** [taketoyoshida/ToTH-Client#68]
### TODO (実装する内容)

今の所、二人のプレイヤーは移動と攻撃のフェーズごとに行動を両者同時に指定して行うことになってるけど、これ処理を考えるとかなり無理がない？
移動フェーズの場合には
- 移動先がかち合ったらそのマスに二人入れるのか
- 二人入った場合立ち絵はどうするのか
- 入れないなら処理はどうするのか

攻撃フェーズの場合には
- 二人同時に獲物を攻撃して仕留めた場合どちらの得点になるのか
- お互いを攻撃して相打ちになったらどうするのか
- 片方が獲物を仕留めてもう片方がそのプレイヤーを倒した場合、獲物を仕留めたプレイヤーに点は入るのか

こんなくらいには問題が山積しているわけでござるが

### Impact (実装による変更の影響範囲)

Gameクラス壊れちゃ^〜う

### Note (補足・考慮すべきこと)

コマンドを同時決定するゲームで思いつくのはポケモンだけど、あれは行動速度の概念があるからねえ
今から新しく行動速度の概念を追加するでござるかあ？

**Comment by kaneko-shoi** [comment]
一つの解決策としてこの期に及んでアクティブタイムバトルにするという手はある
移動や攻撃に参照するのは行動ポイントだから、行動ポイントを「初期配布+時間経過で少しずつ回復」とすれば、動作のかち合いは気にしなくて良くなる
イメージとしてはBlueReflectionの行動ゲージとかFF5以降のFFのATBゲージとか

**Comment by nagry15** [comment]
終了ターンを20ターンとかにして、ターン毎に先行後攻を入れ替えるようにしたら少しは公平になるかな、、、？新しくステータス増やすのはちょっと大変かも

**Comment by kaneko-shoi** [comment]
それもありかあ
とはいえ先行が一方的に有利だからなあ
ターン終了時の残り行動力を参照して先行後行を決めるとかは思いついたけどねー
行動力が同値ならランダムとか？

**Comment by nagry15** [comment]
最悪全ターン先行と後攻はランダムでもいいかもね、公平性っていう観点なら

**Comment by kaneko-shoi** [comment]
それは流石にランダム性強すぎるような…

**Comment by nagry15** [comment]
これ、ひとまずもう先手後手を決めたので解決しました。ゲームバランスは一旦置いときます。
